title: STOGUASAI Statyba
description: Profesionalios statybos ir plėtros paslaugos
baseurl: "/"
url: "https://stoguasai.lt"

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-relative-links

# Navigation
nav:
  - title: Pradžia
    url: /
  - title: Apie
    url: /about/
  - title: Paslaugos
    url: /services/
  - title: Projektai
    url: /projects/
  # - title: Komanda
  #   url: /team/
  - title: Kontaktai
    url: /contact/